### ISSUE TITLE
Handler signature with slack command name

### ISSUE THREAD

**Issue by barryvdh** [spatie/laravel-slack-slash-command#12]
I tried some thing, and generally this seems like a very nice way to handle Slack commands :)

What is kind of bugging me, is that you define the slack command inside your job. From your blog, the `paolo` part:

```protected $signature = 'paolo dns {domain}';```

You have to define the command in the slack config, so if I want to use `/ops` or `/bot` or whatever, the signature changes. This isn't much of a problem for my own, but it makes it hard to share handlers. (Eg. in this package)

I guess it kind a depends on if people use just 1 command for everything, or create multiple slash commands for each one. But as you need to register/setup each slack command, I would assume it would make more sense to have just 1 slack command for all handlers.

I realise you already tagged v1, so BC breaks are not preferred. Possible solutions:
 - Add a global commandname, which skips the commandname check

```protected $signature = '* dns {domain}';```

- Create a new SignatureHandler class or add an option to skip the check and omit the name.

(Downside; those commands would be available on each slack command)

**Comment by glensc** [comment]
well. i'll throw in another use case:

as slack does not have "staging" server, and i wish  to develop the thing, i need to add new `/test_command` that i can develop under and have the other instance as "production" with `/command`. with the current approach i must modify sourcecode to be able to develop.

what's the reosolution here? this issue seems just closed with no response?

**Comment by barryvdh** [comment]
The pr to support regex was added, so you can use * or command* to support command and command_test
