### ISSUE TITLE
Discussion around Help command, SlackSlashCommandException, CatchAll improvments

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravel-slack-slash-command#24]
Pinging @barryvdh 

First of all thanks for all the work you did on this package.

I've opened this issue to discuss a few things regarding your PRs before tagging a new version.

- I've refactored that `CatchAll` command a bit for readability, could you tests if it works properly in your app?
- in one of the PR's you've added `validate` to `SignatureHandler`. Is that method necessary?
- We have [some extensive docs on this package](https://docs.spatie.be/laravel-slack-slash-command/v1/introduction). If you have the time, I'd appreciate if you could add some info on your changes. But don't feel obligated to do this in any way.
- On first thought there are now breaking changes, so I would probably tag a new feature version. Have I missed any breaking changes?

**Comment by barryvdh** [comment]
The validate should imho have been called already, similar to artisan commands. Now the signature is not validated by default, but to avoid BC breaking,  you can call it from without your own handler ($this->validate()) to force validation exceptions when missing data,  instead of checking the parameters yourself. But I would have assumed that to be intended behavior, so you could also do that and regard it as a 'fix' (not sure where, perhaps in the controller?) 

Strictly speaking, internal exceptions are now swallowed in the controller to provide meaningful messages. Bit sure if anyone relies on that to be different, because it mostly means your app doesn't work correctly or throws html errors. 
Don't really recall BC breaks otherwise.

**Comment by freekmurze** [comment]
I've tested out the changes in our own bot and all seems to work well.

A new version `1.1.0` was tagged.

Thanks again for your work.

Have fun using the package!

**Comment by barryvdh** [comment]
I see you toyed with validating all signatures, but assume you noticed that would break the looping through handlers ;)  You could do it in the controller, or call a run method in your controller, so you can define pre/post stuff in the handle method, similar to Laravel. 

Also,  I don't think All exceptions are caught,  so perhaps we would want to transform all non-slack exceptions to SlashExceptions also?

**Comment by freekmurze** [comment]
I'd accept PRs for validating the signatures and catching all exceptions.

**Comment by barryvdh** [comment]
Ok done :) #32 and #33

**Comment by freekmurze** [comment]
👍 

`v.1.1.1` contains the changes in #32 and #33
