### ISSUE TITLE
Question - Can I hide the channel message?

### ISSUE THREAD

**Issue by bloodf** [spatie/laravel-slack-slash-command#71]
I want to know if its possible to hide the invoker message on channel.

![image](https://user-images.githubusercontent.com/1626923/44237535-37957a00-a187-11e8-8aeb-d756a5483adb.png)
 
When the Bot get the commands don`t need to show the user calling command/.

**Comment by royduin** [comment]
Related: #43, did you figure this out @bloodf?

**Comment by royduin** [comment]
Seems like it's not possible: https://api.slack.com/interactivity/slash-commands#responding_to_a_command

> When the `response_type` is `in_channel`, both the response message and the initial Slash Command typed by the user will be shared in the channel:

**Comment by nikhiltri** [comment]
I think what's happening here is that a new message is being posted to the channel, when the original message could actually be updated. I see two commands in the Slack API that seem relevant:

* https://api.slack.com/methods/chat.postMessage
* https://api.slack.com/methods/chat.update

I'm assuming the handlers are using the `chat.postMessage` command, but I can't find any reference to it in order to change it to use a different API method.
